// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Data;

#nullable disable

namespace OnlineStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821162228_HardenAuthenticationAndDataIntegrity")]
    partial class HardenAuthenticationAndDataIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity", "[Quantity] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CartId = 3,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CartId = 4,
                            ProductId = 9,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men and women clothing",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sports and casual shoes",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Useful accessories and gadgets",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPrice", "[UnitPrice] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            ProductName = "Wireless Mouse",
                            Quantity = 1,
                            UnitPrice = 25m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            ProductName = "Mechanical Keyboard",
                            Quantity = 1,
                            UnitPrice = 70m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 8,
                            ProductName = "Smart Watch",
                            Quantity = 1,
                            UnitPrice = 120m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 7,
                            ProductName = "Casual Sneakers",
                            Quantity = 1,
                            UnitPrice = 65m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 6,
                            ProductName = "Running Shoes",
                            Quantity = 1,
                            UnitPrice = 80m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 8,
                            ProductName = "Smart Watch",
                            Quantity = 1,
                            UnitPrice = 70m
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Status", "[Status] IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')");

                            t.HasCheckConstraint("CK_Orders_TotalPrice", "[TotalPrice] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 95m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            TotalPrice = 120m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Processing",
                            TotalPrice = 65m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalPrice = 150m,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_Products_Stock", "[Stock] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Comfortable wireless mouse for everyday use",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 25m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "RGB mechanical keyboard for gaming and work",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 70m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Fast charging USB-C wall charger",
                            ImageUrl = "https://images.unsplash.com/photo-1583863788434-e58a36330cf0",
                            IsActive = true,
                            Name = "USB-C Charger",
                            Price = 35m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Comfortable cotton T-Shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
                            IsActive = true,
                            Name = "Classic T-Shirt",
                            Price = 20m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Warm casual hoodie for everyday wear",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
                            IsActive = true,
                            Name = "Hoodie",
                            Price = 45m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Lightweight running shoes for sports",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
                            IsActive = true,
                            Name = "Running Shoes",
                            Price = 80m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Modern casual sneakers",
                            ImageUrl = "https://images.unsplash.com/photo-1549298916-b41d501d3772",
                            IsActive = true,
                            Name = "Casual Sneakers",
                            Price = 65m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Smart watch with fitness tracking",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
                            IsActive = true,
                            Name = "Smart Watch",
                            Price = 120m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Water resistant backpack for daily use",
                            ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
                            IsActive = true,
                            Name = "Backpack",
                            Price = 40m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Adjustable desk phone stand",
                            ImageUrl = "https://images.unsplash.com/photo-1586953208448-b95a79798f07",
                            IsActive = true,
                            Name = "Phone Stand",
                            Price = 15m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Very good mouse and comfortable to use",
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good smart watch with useful features",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Very comfortable shoes",
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Good quality and comfortable",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Excellent keyboard for gaming",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Admin', 'Customer')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jenin",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohammed@gmail.com",
                            Name = "Mohammed Alqerem",
                            NormalizedEmail = "MOHAMMED@GMAIL.COM",
                            Password = "AQAAAAIAAYagAAAAEJ2wyfnuNORBZAX4OEmJZkWIHaa1yGwVQ+NWaLrSxeM9AZhXq2N10Si1w5TV2sjqkA==",
                            Phone = "0599000001",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nablus",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmad@gmail.com",
                            Name = "Ahmad Ali",
                            NormalizedEmail = "AHMAD@GMAIL.COM",
                            Password = "AQAAAAIAAYagAAAAEKhKgPLuSh6I8xZe/x+WyHyXiphNVT2/1mppogy0X2lv510pcGtFpr22bGERXnCZvA==",
                            Phone = "0599000002",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ramallah",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara@gmail.com",
                            Name = "Sara Khaled",
                            NormalizedEmail = "SARA@GMAIL.COM",
                            Password = "AQAAAAIAAYagAAAAEI9pAV+19TzA1Blbt0DPTjNoPHjZ9Og8CSHeZqEX4iNYSyNu3Qsb/iNN63xmyhvaUw==",
                            Phone = "0599000003",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hebron",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar@gmail.com",
                            Name = "Omar Hassan",
                            NormalizedEmail = "OMAR@GMAIL.COM",
                            Password = "AQAAAAIAAYagAAAAENeCscWzBfbMGK0nvla29rD7/nc+az5LPNRZw9hEYdh38r5imVSV9A6Fjay4LIEFvw==",
                            Phone = "0599000004",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithOne("Cart")
                        .HasForeignKey("OnlineStore.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.CartItems", b =>
                {
                    b.HasOne("OnlineStore.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Models.OrderItems", b =>
                {
                    b.HasOne("OnlineStore.Models.Orders", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.HasOne("OnlineStore.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineStore.Models.Reviews", b =>
                {
                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineStore.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineStore.Models.Users", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
