// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Data;

#nullable disable

namespace OnlineStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            CartId = 3,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CartId = 4,
                            ProductId = 9,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men and women clothing",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sports and casual shoes",
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Useful accessories and gadgets",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 70.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 80.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 70.00m
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            TotalPrice = 95.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Shipped",
                            TotalPrice = 120.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Processing",
                            TotalPrice = 65.00m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPrice = 150.00m,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Comfortable wireless mouse for everyday use",
                            ImageUrl = "mouse.jpg",
                            Name = "Wireless Mouse",
                            Price = 25.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "RGB mechanical keyboard for gaming and work",
                            ImageUrl = "keyboard.jpg",
                            Name = "Mechanical Keyboard",
                            Price = 70.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Fast charging USB-C wall charger",
                            ImageUrl = "charger.jpg",
                            Name = "USB-C Charger",
                            Price = 35.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Comfortable cotton T-Shirt",
                            ImageUrl = "tshirt.jpg",
                            Name = "Classic T-Shirt",
                            Price = 20.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Warm casual hoodie for everyday wear",
                            ImageUrl = "hoodie.jpg",
                            Name = "Hoodie",
                            Price = 45.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Lightweight running shoes for sports",
                            ImageUrl = "running-shoes.jpg",
                            Name = "Running Shoes",
                            Price = 80.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Modern casual sneakers",
                            ImageUrl = "sneakers.jpg",
                            Name = "Casual Sneakers",
                            Price = 65.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Smart watch with fitness tracking",
                            ImageUrl = "smart-watch.jpg",
                            Name = "Smart Watch",
                            Price = 120.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Water resistant backpack for daily use",
                            ImageUrl = "backpack.jpg",
                            Name = "Backpack",
                            Price = 40.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Adjustable desk phone stand",
                            ImageUrl = "phone-stand.jpg",
                            Name = "Phone Stand",
                            Price = 15.00m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Very good mouse and comfortable to use",
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good smart watch with useful features",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Very comfortable shoes",
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Good quality and comfortable",
                            CreatedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Excellent keyboard for gaming",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Rating = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jenin",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohammed@gmail.com",
                            Name = "Mohammed Alqerem",
                            Password = "123456",
                            Phone = "0599000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nablus",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmad@gmail.com",
                            Name = "Ahmad Ali",
                            Password = "123456",
                            Phone = "0599000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ramallah",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@gmail.com",
                            Name = "Sara Khaled",
                            Password = "123456",
                            Phone = "0599000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hebron",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@gmail.com",
                            Name = "Omar Hassan",
                            Password = "123456",
                            Phone = "0599000004"
                        });
                });

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithOne("Cart")
                        .HasForeignKey("OnlineStore.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.CartItems", b =>
                {
                    b.HasOne("OnlineStore.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Models.OrderItems", b =>
                {
                    b.HasOne("OnlineStore.Models.Orders", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.HasOne("OnlineStore.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineStore.Models.Reviews", b =>
                {
                    b.HasOne("OnlineStore.Models.Products", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Models.Users", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineStore.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineStore.Models.Orders", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OnlineStore.Models.Products", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineStore.Models.Users", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
